import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar";
import { Footer } from "@/components/footer";
import AuthProvider from "@/providers/auth-provider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={outfit.className}
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100svh",
          }}
        >
          <Navbar />
          <main className="p-10 flex-1">{children}</main>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
